# Generated by Django 5.1.2 on 2024-12-12 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_options'),
        ('orders', '0002_alter_order_options_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='address_id',
            field=models.ForeignKey(db_column='address_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', default='1', on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
            preserve_default=False,
        ),
    ]
