# Generated by Django 5.1.2 on 2024-12-12 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_options'),
        ('orders', '0003_remove_order_address_remove_order_quantity_and_more'),
        ('products', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True},
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_order_product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='No Address Provided', max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product_id'), name='unique_order_product'),
        ),
    ]
