# Generated by Django 5.1.2 on 2024-12-12 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_options'),
        ('orders', '0004_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='address_id',
            field=models.ForeignKey(db_column='address_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.address'),
        ),
    ]
